<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="45" started-at="2015-11-01T23:48:16Z" finished-at="2015-11-01T23:48:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="45" started-at="2015-11-01T23:48:16Z" finished-at="2015-11-01T23:48:16Z">
      <class name="com.innovapath.unittesting.SubStringReplaceTest">
        <test-method status="PASS" signature="testExpSubstringReplace()[pri:0, instance:com.innovapath.unittesting.SubStringReplaceTest@52d455b8]" name="testExpSubstringReplace" duration-ms="16" started-at="2015-11-01T15:48:16Z" description="Test case for Exception" finished-at="2015-11-01T15:48:16Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.innovapath.programingpractice.SubstringReplace.substringReplace(SubstringReplace.java:13)
	at com.innovapath.unittesting.SubStringReplaceTest.testExpSubstringReplace(SubStringReplaceTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExpSubstringReplace -->
        <test-method status="PASS" signature="testNoSubstringReplace()[pri:0, instance:com.innovapath.unittesting.SubStringReplaceTest@52d455b8]" name="testNoSubstringReplace" duration-ms="4" started-at="2015-11-01T15:48:16Z" description="Test case for finding and replace substring not in input string" finished-at="2015-11-01T15:48:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNoSubstringReplace -->
        <test-method status="PASS" signature="testSubstringReplace()[pri:0, instance:com.innovapath.unittesting.SubStringReplaceTest@52d455b8]" name="testSubstringReplace" duration-ms="2" started-at="2015-11-01T15:48:16Z" description="Test case for finding and replace substring in input string" finished-at="2015-11-01T15:48:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSubstringReplace -->
      </class> <!-- com.innovapath.unittesting.SubStringReplaceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
